<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_group_checkMember.proto

namespace Zaly\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.DuckChatGroupCheckMemberResponse</code>
 */
class DuckChatGroupCheckMemberResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.GroupMemberType memberType = 1;</code>
     */
    private $memberType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $memberType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plugin\DuckchatGroupCheckMember::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.core.GroupMemberType memberType = 1;</code>
     * @return int
     */
    public function getMemberType()
    {
        return $this->memberType;
    }

    /**
     * Generated from protobuf field <code>.core.GroupMemberType memberType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\GroupMemberType::class);
        $this->memberType = $var;

        return $this;
    }

}

