<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_session_profile.proto

namespace Zaly\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.DuckChatSessionProfileResponse</code>
 */
class DuckChatSessionProfileResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.AllUserProfile profile = 1;</code>
     */
    private $profile = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Zaly\Proto\Core\AllUserProfile $profile
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plugin\DuckchatSessionProfile::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.core.AllUserProfile profile = 1;</code>
     * @return \Zaly\Proto\Core\AllUserProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Generated from protobuf field <code>.core.AllUserProfile profile = 1;</code>
     * @param \Zaly\Proto\Core\AllUserProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\AllUserProfile::class);
        $this->profile = $var;

        return $this;
    }

}

