<?php

!defined('IN_ONEZ') && exit('Access Denied');
$dbtables=array();

#onez_member
$dbtables['member']=array(
  'idname'=>'userid',
  'fields'=>array(
    array (
      'fieldname' => 'appid',
      'fieldtype' => 'int',
      'mylen' => '11',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'grade',
      'fieldtype' => 'text',
      'mylen' => '20',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'username',
      'fieldtype' => 'text',
      'mylen' => '80',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'password',
      'fieldtype' => 'text',
      'mylen' => '50',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'mobile',
      'fieldtype' => 'text',
      'mylen' => '30',
      'summary' => '联系方式',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'infotime',
      'fieldtype' => 'int',
      'mylen' => '11',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'infoip',
      'fieldtype' => 'text',
      'mylen' => '20',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'updatetime',
      'fieldtype' => 'int',
      'mylen' => '11',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'updateip',
      'fieldtype' => 'text',
      'mylen' => '20',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'province',
      'fieldtype' => '',
      'mylen' => '',
      'summary' => '所在省',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'city',
      'fieldtype' => '',
      'mylen' => '',
      'summary' => '所在市',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'lasttime',
      'fieldtype' => 'int',
      'mylen' => '11',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'lastip',
      'fieldtype' => 'text',
      'mylen' => '20',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'thisip',
      'fieldtype' => 'text',
      'mylen' => '20',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'thistime',
      'fieldtype' => 'int',
      'mylen' => '11',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'logincount',
      'fieldtype' => 'int',
      'mylen' => '11',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'extra',
      'fieldtype' => 'long',
      'mylen' => '',
      'summary' => '',
      'is_index' => '',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'upid',
      'fieldtype' => 'int',
      'mylen' => '11',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'amt',
      'fieldtype' => 'amt',
      'mylen' => '',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'amt_pay',
      'fieldtype' => 'amt',
      'mylen' => '',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'amt_charge',
      'fieldtype' => 'amt',
      'mylen' => '',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
    array (
      'fieldname' => 'amt_lock',
      'fieldtype' => 'amt',
      'mylen' => '',
      'summary' => '',
      'is_index' => '1',
      'is_only' => '',
    ),
  ),
);


return $dbtables;