<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gw_socket_close.proto

namespace Zaly\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway.GwSocketCloseResponse</code>
 */
class GwSocketCloseResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\GwSocketClose::initOnce();
        parent::__construct($data);
    }

}

