<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_accept.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiFriendAcceptResponse</code>
 */
class ApiFriendAcceptResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Site\ApiFriendAccept::initOnce();
        parent::__construct($data);
    }

}

