<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_removeMember.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.group.removeMember
 *
 * Generated from protobuf message <code>site.ApiGroupRemoveMemberRequest</code>
 */
class ApiGroupRemoveMemberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string groupId = 1;</code>
     */
    private $groupId = '';
    /**
     * Generated from protobuf field <code>repeated string userIds = 2;</code>
     */
    private $userIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $groupId
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $userIds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Site\ApiGroupRemoveMember::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string groupId = 1;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->groupId;
    }

    /**
     * Generated from protobuf field <code>string groupId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string userIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserIds()
    {
        return $this->userIds;
    }

    /**
     * Generated from protobuf field <code>repeated string userIds = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->userIds = $arr;

        return $this;
    }

}

