<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_anonymous_login.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.passport.anonymous.login
 * error:
 *     error.passport.anonymous.loginName.occupied
 *
 * Generated from protobuf message <code>site.ApiPassportAnonymousLoginRequest</code>
 */
class ApiPassportAnonymousLoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string loginName = 1;</code>
     */
    private $loginName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $loginName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Site\ApiPassportAnonymousLogin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string loginName = 1;</code>
     * @return string
     */
    public function getLoginName()
    {
        return $this->loginName;
    }

    /**
     * Generated from protobuf field <code>string loginName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginName = $var;

        return $this;
    }

}

