<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_ping.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * No parameters are required.
 *
 * Generated from protobuf message <code>site.ImCtsPingRequest</code>
 */
class ImCtsPingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string random = 1;</code>
     */
    private $random = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $random
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Site\ImCtsPing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string random = 1;</code>
     * @return string
     */
    public function getRandom()
    {
        return $this->random;
    }

    /**
     * Generated from protobuf field <code>string random = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRandom($var)
    {
        GPBUtil::checkString($var, True);
        $this->random = $var;

        return $this;
    }

}

