<?php

// File generated by the installation wizard
// (do not modify manually)

return array(

    // Database settings

    'dbHost'     => '127.0.0.1',
    'dbPort'     => 3306,
    'dbUser'     => 'root',
    'dbPassword' => '',
    'dbName'     => 'mirrormx_customer_chat_pro',

    // Chat application admin user

    'superUser' => 'admin',
    'superPass' => ''
);

?>
